language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: eggplant-emoji
services:
  - mysql
before_install:
  - mysql -u root --password="" < testDBSetup.sql